### ISSUE TITLE
Datastore interface is a bottleneck

### ISSUE THREAD

**Issue by crackcomm** [ipfs/go-datastore#165]
Hey, I just want to raise an issue that datastore interface is a bottleneck for high-performance usage eq. in FUSE mount because it doesn't provide `Seek` or _partial read_ function with `offset` and `size`.

**Comment by crackcomm** [comment]
See [rendered](https://ipfs.io/ipfs/QmZuyxd3SYKfx8su87Dr8ehwrcfhUKhASuBrF7pxjysJwC) [cpuprof](https://ipfs.io/ipfs/QmcRjySUhVUjfH9RgzkuFkMFcJJ65NstSv42x7d7qVZ3h2) from FUSE file access.

The file is read 100x for a single read.

![image](https://user-images.githubusercontent.com/206368/97771087-de347e00-1b39-11eb-87f0-cf9938839be1.png)
![image](https://user-images.githubusercontent.com/206368/97771095-f0aeb780-1b39-11eb-88e1-1324d82ad903.png)

This in turn creates a huge strain on the garbage collector.

Performance could also be potentially improved by using buffer pools.

**Comment by crackcomm** [comment]
It might be beneficial to introduce the concept of the `Open` or `seekable` method that could be used in FUSE.

The `seekable` method can be provided for any byte array, see Rust [`peekable`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.peekable) for an example implementation.

The method `Get` returning `[]byte` for DAGs is fine but we can do better than allocating 250x1MB of `[]byte` to read a 1MB file while reading in 4KB chunks.

In Go, see also [SectionReader](https://golang.org/pkg/io/#SectionReader).

**Comment by aschmahmann** [comment]
This doesn't really seem like a datastore problem as much as an issue in the FUSE implementation.

Sure you could create a `SeekableDatastore` interface that extends `Datastore` and then implement that in some relevant datastores.

However, the application layer (i.e. your FUSE implementation) probably has a better idea of what it's trying to do than a datastore might. For example, if a block of data is 1MiB and you're reading it in 4KiB chunks, but ultimately are likely to be reading the full block of data, you could just read the 1MiB from disk and hold it until the file descriptor closes or some LRU cache is exceeded.

Given that most of the current implementations of the datastore interface that I know of do not implement `Seek`, or `Open` those would have to be implemented.

If you could implement this more efficiently in the application layer we could then figure out if and how it might be extracted to work across more applications.

Note: If you're working with the go-ipfs FUSE implementation I agree that it could use a number of improvements (performance and otherwise). You may want to check through this [issue](https://github.com/ipfs/go-ipfs/issues/5003) to see some work that was done. There was a contributor working on improving FUSE, but it he hasn't had the time to push things along. Perhaps you'd be interested in helping out.

**Comment by djdv** [comment]
@aschmahmann 
>There was a contributor working on improving FUSE, but it he hasn't had the time to push things along. 

That's not the case :^/
I asked the former maintainer to meet with me to discuss design decisions until they stopped responding. Around August I was trying to schedule with you over Slack for a few weeks but nothing ever came of it.

I'm available to work on this if it's something the project wants, but I need someone with authority to discuss direction and decisions with me as well as just generally review things from time to time.
I have a link to the notes about this here: https://github.com/ipfs/go-ipfs/issues/7575#issuecomment-669331633
An example of the type of things that need to be discussed are things such as [what should the config format look like](https://gist.github.com/djdv/8341762e571ef799cf7613f2f3c1f506#file-fs-config-md) and things of similar scope.
I'm willing to do the work on things, I just need to know what direction to go in.

Feel free to reach out and we can collaborate on this.

**Comment by aschmahmann** [comment]
Oh hey @djdv. Didn't mean to offend you at all, sorry if came off like that. If I left you hanging I apologize.

I've been a bit swamped, but things are starting to clear up and we're making plans for next year. I'll reach out so we can catch up and figure out the next steps.

**Comment by crackcomm** [comment]
This in fact might be seen as a problem of go-ipfs FUSE implementation but this will be inherent to any application using datastore interface. This is the reason for the issue.

I also think that datastore user applications could be improved as @aschmahmann said but this will be putting lipstick on a pig.

In the case of ds-flatfs, current [implementation](https://github.com/ipfs/go-ds-flatfs/blob/master/util_unix.go#L15) can be easily improved in many ways.

@djdv, because of the garbage collector in Go, optimizations are less obvious than in most other languages.

If the user can't manage the `[]byte`, the interface problem will continue creating more and more strain on GC.

**Comment by crackcomm** [comment]
I think some might be concerned about backward compatibility and the issue of porting all libraries at once, this is not necessary when changing it in such a small way. A new datastore method can be added to the interface, keeping `Get` in place and adding wrappers with [`NewReader`](https://golang.org/pkg/bytes/#NewReader), [`NopCloser`](https://golang.org/pkg/io/ioutil/#NopCloser)  etc.

The main problem is allocating new byte slices on each call to `Get`. Perfectly we would return `buffer.Bytes()` from `Get` using a wrapper in the end, not vice-versa.

In turn, this would allow us to provide alternative lazy-loading of values returned by the datastore interface.

The same happens when you open a file on your file system.

**Comment by aschmahmann** [comment]
FlatFS is only one of many datastores using these interfaces (Badger, LevelDB, S3, Azure, Memory, Pebble, ...) there's nothing wrong with adding more to go-ds-flatfs and then checking for optimizations if the datastore supports it.

If it turns out more than one or two databases support the given functionality we can talk about adding a new extension interface (e.g. TTLStore), but until then Go let's you just check the interface type without needing to declare that interface globally.

**Comment by crackcomm** [comment]
@aschmahmann indeed maybe that could be _extension_ using Go interface casting.

**Comment by djdv** [comment]
@crackcomm 
>See rendered cpuprof from FUSE file access.
The file is read 100x for a single read.

Curious to see what the flamegraph looks like on this branch: https://github.com/djdv/go-ipfs/tree/tmp
Would you be willing to run it?

>It might be beneficial to introduce the concept of the Open or seekable method that could be used in FUSE.

I don't remember much about the original fuse implementation's use of the Datastore API directly, but I can say that in the branch above,  a FileSystem interface [is defined](https://github.com/djdv/go-ipfs/blob/4abf41dc2a630ab7e52a94c4dcb4fd8c22a3f034/filesystem/system.go#L18) which is used to [interface with FUSE ](https://github.com/djdv/go-ipfs/blob/4abf41dc2a630ab7e52a94c4dcb4fd8c22a3f034/core/commands/filesystem/manager/host/fuse/host.go#L18) and [other host APIs](https://github.com/djdv/go-ipfs/blob/4abf41dc2a630ab7e52a94c4dcb4fd8c22a3f034/core/commands/filesystem/manager/host/9p/host.go#L45).
The "[Files](https://github.com/djdv/go-ipfs/blob/4abf41dc2a630ab7e52a94c4dcb4fd8c22a3f034/filesystem/file.go)" returned from it have seeking as part of their interface.

I suppose these things are considered to be a bridge between the 'File System' and 'Application' layers.

For example, we're implementing `fuse`, as an application `ipfs mount`. Our implementation utilizes the APIs of the existing filesystems, such as [Unix FS, MFS, and other CoreAPI methods ](https://github.com/djdv/go-ipfs/tree/4abf41dc2a630ab7e52a94c4dcb4fd8c22a3f034/filesystem/interface) which all incorporate their own forms of seeking, caching, flushing, etc.
Either through their API, or added/wrapped in some way by us.
Rather than manipulating the datastore directly ourselves (in our application layer).

A good example of this is the [UFS wrapper](https://github.com/djdv/go-ipfs/blob/tmp/filesystem/interface/ufs/file.go)
There is some complexity around making a reference counted, shared object, but ultimately we're just wrapping the existing [dag modifier library](https://pkg.go.dev/github.com/ipfs/go-unixfs/mod), which implements its own cache, seeking, flushing, etc. and we just pass requests through to it.

**Comment by aschmahmann** [comment]
As was mentioned above given that this request is coming from an application layer request (a FUSE implementation of go-ipfs wants to be able to read partial file data) and that there are a large number of steps and refactors that would be required in order to provide that functionality natively rather than on top of the application layer (e.g. by just caching the bytes instead of repeatedly retrieving them) I'm going to close this issue.

For context some of the refactors that might be required to make this work include:
- Refactor all in use datastores to allow partial retrieval
  - If it turns out some of the existing datastores don't support it then the application layer needs to figure out how to deal with both gracefully -> 😢
- Refactor all consumer interfaces and structs that consume the datastore to expose partial retrieval (e.g. blockstore and implementations)
   - Make sure not to run into issues with the blockstore no longer outputting verifiable data that when hashed matches a CID
- Refactor application layer to take advantage of partial retrieval

If someone is interested in this I'd recommend going from the application layer downwards rather than from the lowest layer interface upwards. Go makes it so you can just make new interfaces and do type checking on them rather than needing to change the base interface declaration which makes this even easier to do.
