### ISSUE TITLE
Delete old, unused datastores.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-datastore#76]
Having to maintain old, unused, untested code is a pain (they won't work anyways because most of them haven't really been tested).

**Comment by magik6k** [comment]
List of what is actually used and how (chocked by searching for usages on latest gx version used by go-ipfs):
* `callback`
  * Used in `coalesce` datastore tests (which is not used)
  * Used in `tiered` datastore tests (which is not used)
* `coalesce`
  * doesn't appear to be used by anything
* `elastigo`
  * ...
  * not used
* `fs`
  * not used
  * we have flatfs
  * it's a tiny, simple implementation of persistent datastore which can be used by anyone who wants to use this package
    * it may be buggy
    * we have flatfs
* `keytransform`
  * used by `namespace`
* `mount`
  * not used
* `namespace`
  * Used by `mount`, `syncmount`, in go-ipfs for `blackstore`, `filestore`
* `panic`
  * not used
  * ...
  * I mean, it may be useful to debug some weird issue, though I'd much rather just use conditional breakpoints.
* `sync`
  * used all over the place in go-ipfs
* `syncmount`
  * used in go-ipfs
* `tiered`
  * not used
  * /might/ be useful, though it doesn't implement batching so I'd say we should drop it, and if anyone wants it back, VCS will still have it.
* `timecache`
  * Same as above

Datastores in basic_ds.go:
* `MapDatastore`:
  * used in many tests everywhere
* `NullDatastore`:
  * Used in some tests
* `LogDatastore`:
  * Usable in go-ipfs (though mdns needs to be disabled due to a bug)

So I'd say we should remove `callback`, `coalesce`, `elastigo`, `fs`, `mount`, `tiered` and `timecache`, @Stebalien LGTY?

**Comment by magik6k** [comment]
And probably just rename `syncmount` to `mount`

**Comment by Stebalien** [comment]
LGTM. @whyrusleeping? You should probably sign off on this since we're deleting code.

**Comment by whyrusleeping** [comment]
@magik6k @Stebalien lets make a tag on the commit the code exists in before we delete it, and note it in an issue somewhere. After that, SGTM

**Comment by kevina** [comment]
Some of those might be useful as examples, such as `fs` and may be worth keeping around.  Maybe we can move those to the examples directory.

**Comment by Stebalien** [comment]
I agree that some of them might be useful (e.g., tiered, timecache) but I'd actually like to get rid of the `fs` one, even if we keep the others. It's insecure/broken by default (it uses the key names as the file names without modifying them).

**Comment by kevina** [comment]
The idea was to move it to the examples directory as use it as documentation, not to keep around as a useful datastore.  However, I am not set on the idea, any other trivial datastore could serve the same purpose.

**Comment by Stebalien** [comment]
Yeah, I see the value as documentation... I guess we could just put a big warning saying "don't actually do it this way".

**Comment by kevina** [comment]
I would also move it under `examples/fs`.
